### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present

### ISSUE THREAD

**Issue by zzvilzz** [kevinselwyn/fast#1]
I cloned the repo and run index.html file and nothing is working. I check browser log and found this:

"Failed to load https://api.fast.com/netflix/speedtest?https=true&token=YXNkZmFzZGxmbnNkYWZoYXNkZmhrYWxm&urlCount=5: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 500."

Can anyone suggest a fix for this?

**Comment by kevinselwyn** [comment]
You need to view `index.html` on a server environment and not off the filesystem.

Try running this in the directory where you cloned the project:

`python -m SimpleHTTPServer 8000`

Navigate to: `http://localhost:8000`

**Comment by mram0509** [comment]
I am viewing index.html in a server environment and still getting the issue. What's the fix for this? I am using Chrome 72.0.3626
Running the code as is I get the following error:
Access to XMLHttpRequest at 'http://api.fast.com/netflix/speedtest?https=true&token=YXNkZmFzZGxmbnNkYWZoYXNkZmhrYWxm&urlCount=3' from origin 'http://www.sample.com' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'null' that is not equal to the supplied origin.

I tried adding this to the xhr object:
xhr.setRequestHeader("Access-Control-Allow-Origin", "*");

Now the error has to do with pre-flight issues:
index.html:1 Access to XMLHttpRequest at 'http://api.fast.com/netflix/speedtest?https=true&token=YXNkZmFzZGxmbnNkYWZoYXNkZmhrYWxm&urlCount=3' from origin 'http://www.sample.com' has been blocked by CORS policy: Request header field access-control-allow-origin is not allowed by Access-Control-Allow-Headers in preflight response.
